#!/bin/bash

CURL='/usr/bin/curl'
URL='https://sns.ift.org.mx:8081/sns-frontend/planes-numeracion/descarga-publica.xhtml'
CURLARGS='-sD -'

SEND_CURL="$($CURL $CURLARGS $URL)"
arr=($SEND_CURL)

i=0
for var in "${arr[@]}"
do
  if [[ $var == *"FRONTAPPID="* ]]; then
    FRONTAPPID=$(echo "$var" | sed 's/.*FRONTAPPID=\(.*\);.*/\1/')

  fi
  if [[ $var == *"id=\"javax.faces.ViewState\""* ]]; then
  	VIEWSTATE=$(echo ${arr[i+1]} | sed 's/.*"\(.*\)".*/\1/')

  fi
  ((i++))
done

($CURL -X POST -H "Cookie: primefaces.download=true;FRONTAPPID=$FRONTAPPID" -H "Content-Type: application/x-www-form-urlencoded" -H "Cache-Control: no-cache" -d 'FORM_planes=FORM_planes&FORM_planes:BTN_planPublico1=BTN_planPublico1&javax.faces.ViewState='$VIEWSTATE'' "https://sns.ift.org.mx:8081/sns-frontend/planes-numeracion/descarga-publica.xhtml") > test.zip
